[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-run-functions"
  [plugins.inputs]
    functions = "functions"

[build.environment]
  # Variáveis de ambiente são configuradas diretamente no Netlify UI

[build.processing]
  command = "npm run notify-initializing"

[build.deploy]
  command = "npm run notify-building"

[build.cleanup]
  command = "npm run notify-deploying"

[build.post-processing]
  command = "npm run notify-cleanup"

[build.done]
  command = "npm run notify-post-processing"

[build.failed]
  command = "npm run notify-failure"