[build]
  command = "npm run build"

[build.environment]
  DEV_NOTIFICATION = "https://<URL_DO_SEU_PROJETO_GGNOTIF>.netlify.app/.netlify/functions/send-discord-notification"

[build.processing]
  command = "npm run notify-initializing"

[build.deploy]
  command = "npm run notify-building"

[build.cleanup]
  command = "npm run notify-deploying"

[build.post-processing]
  command = "npm run notify-cleanup"

[build.done]
  command = "npm run notify-post-processing"

[build.failed]
  command = "npm run notify-failure"

[[edge_functions]]
function = "hello"
path = "/test"